baseURL = "https://learn.pelle.io/"
languageCode = "en-us"
title = "learn.pelle.io"
staticDir = ["static"]

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "green"
disableInlineCopyToClipBoard = true
