#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -eu

prefix=$(realpath "${DIR}/../../")
STEP_DIR=${DIR#${prefix}/}

ARTIFACTS_DIR="${ARTIFACTS_DIR:-}"
TODO_PROJECT_DIR="${TODO_PROJECT_DIR:-}"

for var in "${TODO_PROJECT_DIR}" \
  "${ARTIFACTS_DIR}" ; do
  if [ -z "$var" ] ; then
    echo "Environment variable missing"
    exit 1
  fi
done

function task_test {
  (
    cd ${ARTIFACTS_DIR}/${STEP_DIR}/todo-server
    ./gradlew idea eclipse build
  )
}

function task_generate {
  echo "generating ${STEP_DIR}"
  mkdir -p ${ARTIFACTS_DIR}/${STEP_DIR}
  (
    cd ${TODO_PROJECT_DIR}
    rsync -av --progress . ${ARTIFACTS_DIR}/${STEP_DIR} --exclude build.gradle --exclude .gradle --exclude settings.gradle --exclude FrontendContent.java  --exclude node_modules --exclude .idea --exclude build --exclude out
  )
  (
    cd ${DIR}
    rsync -av --progress . ${ARTIFACTS_DIR}/${STEP_DIR} --exclude run
    cd ${ARTIFACTS_DIR}/${STEP_DIR}
    mv gradlew* todo-server
    mv gradle todo-server/gradle

  )
}

CMD=${1:-}
shift || true
case ${CMD} in
  test) task_test ;;
  generate) task_generate ;;
esac
