#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -eu

HUGO_DIR="${DIR}/hugo"
TEMP_DIR="${DIR}/build"
CONTENT_DIR="${HUGO_DIR}/content"
ARTEFACTS_DIR="${DIR}/artefacts"
SOURCES_DIR="${DIR}/sources"
STEPS_DIR="${SOURCES_DIR}/steps"
TODO_PROJECT_DIR="${SOURCES_DIR}/todo_project"

function generate_and_insert_snippets() {

  echo "generating snippets for '${ARTEFACTS_DIR}'"
  (
    cd ${ARTEFACTS_DIR}
    for file in $(git ls-tree -r master --name-only .); do
      TEMP_DIR=${TEMP_DIR} bundle exec ruby ${DIR}/scripts/extract_snippets.rb ${file}
    done
  )

  echo "inserting snippets for '${HUGO_DIR}/content'"
  (
    cd ${HUGO_DIR}/content
    for file in $(git ls-tree -r master --name-only .); do
      ARTEFACTS_DIR=${ARTEFACTS_DIR} TEMP_DIR=${TEMP_DIR} bundle exec ruby ${DIR}/scripts/insert_snippets.rb ${file}
    done
  )

}

function task_generate {
  ensure_environment

  echo "running steps runfiles for '${STEPS_DIR}'"
  local last_step_dir=''
  for RUN_FILE in $(find ${STEPS_DIR} -name run | sort); do
    local step_dir=$(dirname ${RUN_FILE})

    prefix=$(realpath "${STEPS_DIR}")
    step_dir=${step_dir#${prefix}/}

    echo "running step runfile '${RUN_FILE}'"
    STEPS_DIR=${STEPS_DIR} LAST_STEP_DIR=${last_step_dir} STEP_DIR=${step_dir} TODO_PROJECT_DIR=${TODO_PROJECT_DIR} ARTEFACTS_DIR=$(readlink -f ${ARTEFACTS_DIR}) ${RUN_FILE} generate
    last_step_dir=${step_dir}
  done

  generate_and_insert_snippets

  (
    cd ${ARTEFACTS_DIR}
    for source_file in $(git ls-tree -r master --name-only .); do
      echo "cleaning file ${source_file}"
      sed -i '/snippet:/d' ${source_file}
    done
  )

}


function ensure_environment {
  if [ ! -d ${ARTEFACTS_DIR} ]; then
      mkdir -p ${ARTEFACTS_DIR}
  fi

  if [ ! -d ${TEMP_DIR} ]; then
    mkdir ${TEMP_DIR}
  fi
}

function ensure_full_project_is_buildable {
  (
    cd ${TODO_PROJECT_DIR}
    ./gradlew build
  )
}

function task_test {
  ensure_full_project_is_buildable
  echo "testing all artefacts"
  for RUN_FILE in $(find ${STEPS_DIR} -name run); do
    TODO_PROJECT_DIR=${TODO_PROJECT_DIR} ARTEFACTS_DIR=${ARTEFACTS_DIR} ${RUN_FILE} test
  done
}

function task_build {
  ensure_environment
  task_generate
  cd ${HUGO_DIR}
  hugo
}

function task_hugo {
  cd ${HUGO_DIR}
  hugo serve
}

function task_clean {
  rm -rf ${TEMP_DIR}
}

function task_deploy {
  ncftpput -R -v -u ${FTP_USERNAME:-$(pass 'learn.pelle.io/ftp/userid')} -p ${FTP_PASSWORD:-$(pass 'learn.pelle.io/ftp/password')} ftp.pelle.io / ${HUGO_DIR}/public/*
}

function task_usage {
  echo "Usage: $0 generate | clean | test | build | deploy | hugo"
  exit 1
}

CMD=${1:-}
shift || true
case ${CMD} in
  generate) task_generate ;;
  clean) task_clean ;;
  test) task_test ;;
  build) task_build ;;
  hugo) task_hugo ;;
  deploy) task_deploy ;;
  *) task_usage ;;
esac
